### ISSUE TITLE
Changed meaning of statsd counter with v == 0

### ISSUE THREAD

**Issue by pietern** [circonus-labs/circonus-agent#53]
I just updated my NAD COSI setup to use the new agent and noticed a counter that should equal 0 under nominal conditions (an error counter) have a value equal to the number of "good" events. I found the offending line in the statsd parsing code here: https://github.com/circonus-labs/circonus-agent/blob/d0f65a472a87037291b3feca0371d7f69977a82e/internal/statsd/metrics.go#L155-L157

Is this intentional? If yes, is there another way to have a counter with value 0?

Thanks!

**Comment by maier** [comment]
No, it is *not* intentional. Fixing.

**Comment by maier** [comment]
#54 addresses this released as v0.19.1

**Comment by pietern** [comment]
Thank you for the fix and release!
