### ISSUE TITLE
Unable to install on SmartOS (illumos)

### ISSUE THREAD

**Issue by jussisallinen** [circonus-labs/circonus-agent#67]
Trying to install on SmartOS results in following error:

```
Started Circonus One step Install on October  8, 2019 at 09:07:06 AM UTC
Initializing cosi-install
Parsing command line parameters
Verifying COSI support for OS
        Attempt SunOS(variant) detection
        Found /etc/release - using 'SmartOS 20190925T185257Z x86_64'
        Looking up SunOS SmartOS v20190925T185257Z.x86_64 amd64.

ERROR: Unexpected response received from COSI request 'invalid system 'vers' specified
|400'. Try curl -v 'https://setup.circonus.com/package/?type=SunOS&dist=SmartOS&vers=20190925T185257Z.x86_64&arch=amd64' to see full transaction details.
```

Noticed that there's SMF manifest added recently so it hints at illumos support:
https://github.com/circonus-labs/circonus-agent/pull/66/commits/d68658c14839279853df1d0b2c40620492da103a

**Comment by maier** [comment]
You can install manually, using the solaris or illumos package from the most recent [release](https://github.com/circonus-labs/circonus-agent/releases). The circonus one step install, cosi, does not currently support SmartOS.

**Comment by jussisallinen** [comment]
So I thought, will need to do that and see how to configure it as script seems to automate some part of it.
Guess this issue can be closed then?

**Comment by jussisallinen** [comment]
Managed to get it up and running.

Do I need to define something in particular to get generic metrics working in illumos/SmartOS?

With the default configuration I get Host in Circonus WebUI but no metrics at all.

**Comment by maier** [comment]
Do you get metrics with `curl localhost:2609`? If so, then ensure that the host is reachable from the broker the check is configured on. If the host is behind NAT you'll need to run the agent in reverse mode (`--reverse` on the command line, or enable reverse in the configuration file).

**Comment by jussisallinen** [comment]
Right I didn't notice that it's not reverse by default, the host is behind NAT.

Got it working by enabling reverse:
`{"level":"info","pkg":"server","duration":"72.691533ms","num_metrics":296,"compressed":true,"content_bytes":4398,"time":"2019-10-08T18:11:09.187929004Z","message":"request response"}`
